### ISSUE TITLE
More data

### ISSUE THREAD

**Issue by hi-matbub** [json-faker/jsonfaker#4]
Do you know where to obtain large lists of data? Maybe the US Census? 

Feel free to contribute to the super array in ./functions/helpers/data

**Comment by zootechdrum** [comment]
So you want me to add to the data object?
If so, we should add a list of fake addresses. What do you think?

**Comment by hi-matbub** [comment]
@zootechdrum That would be cool, we have something relevant set up in the npm [fake-things](https://github.com/hi-matbub/fake-things). You could use the `Location()` method to help if you need it.

**Comment by zootechdrum** [comment]
Oh, I skipped over it. What about a list of animals. Can't go wrong with animals lol.

**Comment by hi-matbub** [comment]
@zootechdrum sounds great looking forward to it!
